"""create news tables

Revision ID: bb54b29838bb
Revises: 68fa96153ac3
Create Date: 2026-10-07 17:05:38.471174

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb54b29838bb"
down_revision: str | Sequence[str] | None = "68fa96153ac3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("rss", "kap", name="source_type", native_enum=False, create_constraint=True, length=20),
            nullable=False,
        ),
        sa.Column("source_name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("kap_disclosure_type", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_news_items")),
        sa.UniqueConstraint("content_hash", name=op.f("uq_news_items_content_hash")),
        sa.UniqueConstraint("url", name=op.f("uq_news_items_url")),
    )
    op.create_index(op.f("ix_news_items_published_at"), "news_items", ["published_at"], unique=False)
    op.create_table(
        "news_stock_links",
        sa.Column("news_id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column(
            "match_method",
            sa.Enum(
                "ticker",
                "alias",
                "kap",
                name="match_method",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("match_score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["news_id"],
            ["news_items.id"],
            name=op.f("fk_news_stock_links_news_id_news_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"], ["stocks.id"], name=op.f("fk_news_stock_links_stock_id_stocks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("news_id", "stock_id", name=op.f("pk_news_stock_links")),
    )
    op.create_index(op.f("ix_news_stock_links_stock_id"), "news_stock_links", ["stock_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_news_stock_links_stock_id"), table_name="news_stock_links")
    op.drop_table("news_stock_links")
    op.drop_index(op.f("ix_news_items_published_at"), table_name="news_items")
    op.drop_table("news_items")
    # ### end Alembic commands ###
